### ISSUE TITLE
Remove dependency on rails 4

### ISSUE THREAD

**Issue by untoldone** [eversign/eversign-ruby-sdk#1]
Not entirely clear why there's a dep on rails at all? Makes this gem basically not usable if you're on a recent version of rails ... but also seems like a pretty big dependency burden for a non-rails app otherwise.

**Comment by alexkhalevine** [comment]
We removed version lock on rails, it is used because we relay on ActiveModel. But now you will be able to use it with higher versions of rails as well

**Comment by milanlatinovic** [comment]
Thanks @alexkhalevine , I will mark this and resolved.
