### ISSUE TITLE
Add use_hidden_tags mapping to Document

### ISSUE THREAD

**Issue by alexio49** [eversign/eversign-ruby-sdk#12]
**Is your feature request related to a problem? Please describe.**
In lib/eversign/mappings/document.rb:47 class `Document` is missing `use_hidden_tags` mapping and an accessor in lib/eversign/models/document.rb:4, as described in  https://eversign.com/api/documentation/hidden-tags.

**Describe the solution you'd like**
use_hidden_tags issue should accept 0 or 1 on Document instance

**Describe alternatives you've considered**
monkey patching the class

**Additional context**
https://eversign.com/api/documentation/hidden-tags

**Comment by alexkhalevine** [comment]
Thank you for you contribution, PR is merged and latest gem is pushed to [rubygems](https://rubygems.org/gems/eversign-sdk)
